Create CONTRIBUTING.md
conjurinc/api-node pull request #11
Opened 2020-03-11 19:10 UTC by BradleyBoutcher

- Introduce CONTRIBUTING.md
- Link to general contributing guidelines

2020-03-11 19:13 UTC, BradleyBoutcher commented
Please squash & merge

2020-03-11 21:38 UTC, izgeri commented on CONTRIBUTING.md
> +## Table of Contents
We can probably drop the TOC for a contributing file this short

2020-03-11 21:39 UTC, izgeri requested changes
This is a lower prio repo so feel free to work on others first, but the Testing content in the README should be moved here too

2020-03-25 14:04 UTC, jtuttle commented
@BradleyBoutcher Got time to merge this down soon? Looks like a pretty simple change needed to get it mergeable.

2020-04-15 14:30 UTC, izgeri approved these changes

2020-04-15 14:30 UTC, izgeri requested changes
Ack @BradleyBoutcher I approved without reading my prior message - but it looks like this is still outstanding:
- [ ] the Testing content in the README should be moved here too

2020-04-15 15:36 UTC, izgeri approved these changes

2020-04-15 15:36 UTC, merged